# Generated by Django 3.2.3 on 2021-06-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
