# Generated by Django 3.2.3 on 2021-06-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bp_app', '0002_auto_20210603_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AppUser',
        ),
    ]
